### PR TITLE
Array support for b.exclude() and b.ignore()

### PR DESCRIPTION
**Pull request by bakape**
Simple usability enhancement to prevent long exclude/ignore chains.

### CODE REVIEW

**Comment by terinjokes** [comment]
Can you add tests for this behavior?

**Comment by bakape** [comment]
Correct me, if I'm missing something, but is a test necessary here? The two functions simply recurse with arrays, so a test would involve mimicking the existing tests in a chain. A bit redundant. Of course, if you meant exactly that, no reason it can't be done.

**Comment by christophercrouzet** [comment]
Any news on this one? I wouldn't mind having this merged as it currently is a bit inconsistent with other methods such as `external`, on top of having no idea how to programmatically define a variable number of `exclude`.

**Comment by bakape** [comment]
@christophercrouzet 
Tests added.

**Comment by christophercrouzet** [comment]
Thanks!

**Comment by terinjokes** [comment]
@bakape for the record, I asked for tests not because it was difficult or tricky, but because we don't want to accidentally break it in the future.

This PR looks reasonable. Let's see what another contributor thinks.

**Pull request closed without merging**
