### PR TITLE
Failing test + fix for backtick quotes

### PR DESCRIPTION
**Pull request by TehShrike**
Issue #1782

This issue needs to be fixed in `module-deps`.  I will open a pull request there.

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
in https://github.com/browserify/detective even, i think. thanks for working on this :D

**Comment by TehShrike** [comment]
I'll update this to use `module-deps@2.x` and then it should be good.

**Comment by TehShrike** [comment]
Bumping the dependency on `module-dep`s guarantees that the backtick-supporting version of `detective` will be used.

The tests fail in 0.10 and 0.12 because `detective` doesn't support those versions any more.

**Comment by goto-bus-stop** [comment]
merging since the failures are only on node <4 and tests will pass on master. thanks!

**Pull request merged**
