### PR TITLE
test/bare.js: fix file path

### PR DESCRIPTION
**Pull request by al-k21**
Fixes: https://github.com/browserify/browserify/issues/1809, https://github.com/nodejs/citgm/issues/545

### CODE REVIEW

**Comment by al-k21** [comment]
I believe that my fix has nothing to do with the failing checks, please review @goto-bus-stop.

**Comment by goto-bus-stop** [comment]
Yes the failures are unrelated. The tmpdir is necessary so that the file that the test writes gets cleaned up afterward.

I think the right fix here would be to pass `__dirname: process.cwd()` instead of `__dirname: path.dirname(file)` on line 126. That way we test if the paths are rebased correctly by checking if they match up with the original path.

**Comment by al-k21** [comment]
> The tmpdir is necessary so that the file that the test writes gets cleaned up afterward.

Thanks, that makes sense. 
PR updated.

**Comment by al-k21** [comment]
Hello, is this likely to get merged and released? @goto-bus-stop

**Pull request merged**
