### PR TITLE
Removing a line of code that tried to convince me that I was crazy

### PR DESCRIPTION
**Pull request by TehShrike**

### CODE REVIEW

**Comment by terinjokes** [comment]
@substack Is this supposed to be `opts.transform` per the change here https://github.com/substack/node-browserify/commit/78ca8b73edf9eda641e3a48d77d583c4ac16ffaa?

**Comment by jmm** [comment]
Dupe of #1057.

**Comment by TehShrike** [comment]
This is also fixed in #1262... so, hopefully that will get merged at some point?

**Comment by stevemao** [comment]
Duplicate of #1057.

**Pull request closed without merging**
